version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/no_signal
    environment:
      - DB_HOST=db
      - DB_NAME=no_siganl
      - DB_USER=postgres
      - DB_PASS=root

    command:
      sh -c "
      ./manage.py wait_for_db &&
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - memcached
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=no_siganl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  memcached:
    image: memcached
    ports:
      - '11212:11211'
    entrypoint:
      - memcached
      - -m 64