# Generated by Django 3.2.5 on 2021-07-29 10:24

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210729_1024'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
