# Generated by Django 3.2.5 on 2021-07-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='updated',
            new_name='modified',
        ),
    ]
