# Generated by Django 3.2.5 on 2021-07-29 10:24

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_updated_course_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
