# Generated by Django 3.2.5 on 2021-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210724_1307'),
        ('courses', '0006_auto_20210729_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='accounts.User'),
        ),
    ]
