# Generated by Django 3.2.6 on 2021-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210724_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('s', 'student'), ('t', 'teacher')], default='s', max_length=1),
        ),
    ]
